//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSMVC.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="laporanpenggunaanvaksin", Namespace="http://schemas.datacontract.org/2004/07/RSakitWCF")]
    [System.SerializableAttribute()]
    public partial class laporanpenggunaanvaksin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdBPOMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdLaporanPengField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdRSakitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long NikPasienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoRegisVaksinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoRekamMedisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdBPOM {
            get {
                return this.IdBPOMField;
            }
            set {
                if ((object.ReferenceEquals(this.IdBPOMField, value) != true)) {
                    this.IdBPOMField = value;
                    this.RaisePropertyChanged("IdBPOM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdLaporanPeng {
            get {
                return this.IdLaporanPengField;
            }
            set {
                if ((object.ReferenceEquals(this.IdLaporanPengField, value) != true)) {
                    this.IdLaporanPengField = value;
                    this.RaisePropertyChanged("IdLaporanPeng");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdRSakit {
            get {
                return this.IdRSakitField;
            }
            set {
                if ((object.ReferenceEquals(this.IdRSakitField, value) != true)) {
                    this.IdRSakitField = value;
                    this.RaisePropertyChanged("IdRSakit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long NikPasien {
            get {
                return this.NikPasienField;
            }
            set {
                if ((this.NikPasienField.Equals(value) != true)) {
                    this.NikPasienField = value;
                    this.RaisePropertyChanged("NikPasien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoRegisVaksin {
            get {
                return this.NoRegisVaksinField;
            }
            set {
                if ((object.ReferenceEquals(this.NoRegisVaksinField, value) != true)) {
                    this.NoRegisVaksinField = value;
                    this.RaisePropertyChanged("NoRegisVaksin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoRekamMedis {
            get {
                return this.NoRekamMedisField;
            }
            set {
                if ((object.ReferenceEquals(this.NoRekamMedisField, value) != true)) {
                    this.NoRekamMedisField = value;
                    this.RaisePropertyChanged("NoRekamMedis");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pasien", Namespace="http://schemas.datacontract.org/2004/07/RSakitWCF")]
    [System.SerializableAttribute()]
    public partial class Pasien : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlamatPasienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdPemerintahField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdRSakitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamaPasienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NikPasienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoRegisPasienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoRegisVaksinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoRekamMedisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoTeleponField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlamatPasien {
            get {
                return this.AlamatPasienField;
            }
            set {
                if ((object.ReferenceEquals(this.AlamatPasienField, value) != true)) {
                    this.AlamatPasienField = value;
                    this.RaisePropertyChanged("AlamatPasien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdPemerintah {
            get {
                return this.IdPemerintahField;
            }
            set {
                if ((object.ReferenceEquals(this.IdPemerintahField, value) != true)) {
                    this.IdPemerintahField = value;
                    this.RaisePropertyChanged("IdPemerintah");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdRSakit {
            get {
                return this.IdRSakitField;
            }
            set {
                if ((object.ReferenceEquals(this.IdRSakitField, value) != true)) {
                    this.IdRSakitField = value;
                    this.RaisePropertyChanged("IdRSakit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NamaPasien {
            get {
                return this.NamaPasienField;
            }
            set {
                if ((object.ReferenceEquals(this.NamaPasienField, value) != true)) {
                    this.NamaPasienField = value;
                    this.RaisePropertyChanged("NamaPasien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NikPasien {
            get {
                return this.NikPasienField;
            }
            set {
                if ((object.ReferenceEquals(this.NikPasienField, value) != true)) {
                    this.NikPasienField = value;
                    this.RaisePropertyChanged("NikPasien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoRegisPasien {
            get {
                return this.NoRegisPasienField;
            }
            set {
                if ((object.ReferenceEquals(this.NoRegisPasienField, value) != true)) {
                    this.NoRegisPasienField = value;
                    this.RaisePropertyChanged("NoRegisPasien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoRegisVaksin {
            get {
                return this.NoRegisVaksinField;
            }
            set {
                if ((object.ReferenceEquals(this.NoRegisVaksinField, value) != true)) {
                    this.NoRegisVaksinField = value;
                    this.RaisePropertyChanged("NoRegisVaksin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoRekamMedis {
            get {
                return this.NoRekamMedisField;
            }
            set {
                if ((object.ReferenceEquals(this.NoRekamMedisField, value) != true)) {
                    this.NoRekamMedisField = value;
                    this.RaisePropertyChanged("NoRekamMedis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoTelepon {
            get {
                return this.NoTeleponField;
            }
            set {
                if ((object.ReferenceEquals(this.NoTeleponField, value) != true)) {
                    this.NoTeleponField = value;
                    this.RaisePropertyChanged("NoTelepon");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vaksin", Namespace="http://schemas.datacontract.org/2004/07/RSakitWCF")]
    [System.SerializableAttribute()]
    public partial class Vaksin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdProdusenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdVaksinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoRegisVaksinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdProdusen {
            get {
                return this.IdProdusenField;
            }
            set {
                if ((object.ReferenceEquals(this.IdProdusenField, value) != true)) {
                    this.IdProdusenField = value;
                    this.RaisePropertyChanged("IdProdusen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdVaksin {
            get {
                return this.IdVaksinField;
            }
            set {
                if ((this.IdVaksinField.Equals(value) != true)) {
                    this.IdVaksinField = value;
                    this.RaisePropertyChanged("IdVaksin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoRegisVaksin {
            get {
                return this.NoRegisVaksinField;
            }
            set {
                if ((object.ReferenceEquals(this.NoRegisVaksinField, value) != true)) {
                    this.NoRegisVaksinField = value;
                    this.RaisePropertyChanged("NoRegisVaksin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rumah_Sakit", Namespace="http://schemas.datacontract.org/2004/07/RSakitWCF")]
    [System.SerializableAttribute()]
    public partial class Rumah_Sakit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlamatRSakitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdRSakitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamaRSakitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long NikPasienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoRegisVaksinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoTeleponField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlamatRSakit {
            get {
                return this.AlamatRSakitField;
            }
            set {
                if ((object.ReferenceEquals(this.AlamatRSakitField, value) != true)) {
                    this.AlamatRSakitField = value;
                    this.RaisePropertyChanged("AlamatRSakit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdRSakit {
            get {
                return this.IdRSakitField;
            }
            set {
                if ((object.ReferenceEquals(this.IdRSakitField, value) != true)) {
                    this.IdRSakitField = value;
                    this.RaisePropertyChanged("IdRSakit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NamaRSakit {
            get {
                return this.NamaRSakitField;
            }
            set {
                if ((object.ReferenceEquals(this.NamaRSakitField, value) != true)) {
                    this.NamaRSakitField = value;
                    this.RaisePropertyChanged("NamaRSakit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long NikPasien {
            get {
                return this.NikPasienField;
            }
            set {
                if ((this.NikPasienField.Equals(value) != true)) {
                    this.NikPasienField = value;
                    this.RaisePropertyChanged("NikPasien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoRegisVaksin {
            get {
                return this.NoRegisVaksinField;
            }
            set {
                if ((object.ReferenceEquals(this.NoRegisVaksinField, value) != true)) {
                    this.NoRegisVaksinField = value;
                    this.RaisePropertyChanged("NoRegisVaksin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoTelepon {
            get {
                return this.NoTeleponField;
            }
            set {
                if ((object.ReferenceEquals(this.NoTeleponField, value) != true)) {
                    this.NoTeleponField = value;
                    this.RaisePropertyChanged("NoTelepon");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddPelaporanPenggunaanVaksin", ReplyAction="http://tempuri.org/IService1/AddPelaporanPenggunaanVaksinResponse")]
        bool AddPelaporanPenggunaanVaksin(RSMVC.ServiceReference1.laporanpenggunaanvaksin pelaporan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddPelaporanPenggunaanVaksin", ReplyAction="http://tempuri.org/IService1/AddPelaporanPenggunaanVaksinResponse")]
        System.Threading.Tasks.Task<bool> AddPelaporanPenggunaanVaksinAsync(RSMVC.ServiceReference1.laporanpenggunaanvaksin pelaporan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPasien", ReplyAction="http://tempuri.org/IService1/GetPasienResponse")]
        RSMVC.ServiceReference1.Pasien[] GetPasien();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPasien", ReplyAction="http://tempuri.org/IService1/GetPasienResponse")]
        System.Threading.Tasks.Task<RSMVC.ServiceReference1.Pasien[]> GetPasienAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetVaksin", ReplyAction="http://tempuri.org/IService1/GetVaksinResponse")]
        RSMVC.ServiceReference1.Vaksin[] GetVaksin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetVaksin", ReplyAction="http://tempuri.org/IService1/GetVaksinResponse")]
        System.Threading.Tasks.Task<RSMVC.ServiceReference1.Vaksin[]> GetVaksinAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRumah_Sakit", ReplyAction="http://tempuri.org/IService1/GetRumah_SakitResponse")]
        RSMVC.ServiceReference1.Rumah_Sakit[] GetRumah_Sakit();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRumah_Sakit", ReplyAction="http://tempuri.org/IService1/GetRumah_SakitResponse")]
        System.Threading.Tasks.Task<RSMVC.ServiceReference1.Rumah_Sakit[]> GetRumah_SakitAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : RSMVC.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<RSMVC.ServiceReference1.IService1>, RSMVC.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddPelaporanPenggunaanVaksin(RSMVC.ServiceReference1.laporanpenggunaanvaksin pelaporan) {
            return base.Channel.AddPelaporanPenggunaanVaksin(pelaporan);
        }
        
        public System.Threading.Tasks.Task<bool> AddPelaporanPenggunaanVaksinAsync(RSMVC.ServiceReference1.laporanpenggunaanvaksin pelaporan) {
            return base.Channel.AddPelaporanPenggunaanVaksinAsync(pelaporan);
        }
        
        public RSMVC.ServiceReference1.Pasien[] GetPasien() {
            return base.Channel.GetPasien();
        }
        
        public System.Threading.Tasks.Task<RSMVC.ServiceReference1.Pasien[]> GetPasienAsync() {
            return base.Channel.GetPasienAsync();
        }
        
        public RSMVC.ServiceReference1.Vaksin[] GetVaksin() {
            return base.Channel.GetVaksin();
        }
        
        public System.Threading.Tasks.Task<RSMVC.ServiceReference1.Vaksin[]> GetVaksinAsync() {
            return base.Channel.GetVaksinAsync();
        }
        
        public RSMVC.ServiceReference1.Rumah_Sakit[] GetRumah_Sakit() {
            return base.Channel.GetRumah_Sakit();
        }
        
        public System.Threading.Tasks.Task<RSMVC.ServiceReference1.Rumah_Sakit[]> GetRumah_SakitAsync() {
            return base.Channel.GetRumah_SakitAsync();
        }
    }
}
