//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSakitWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pasien
    {
        public string NikPasien { get; set; }
        public string NoRegisPasien { get; set; }
        public string NoRekamMedis { get; set; }
        public string NamaPasien { get; set; }
        public string AlamatPasien { get; set; }
        public string IdPemerintah { get; set; }
        public string NoRegisVaksin { get; set; }
        public string IdRSakit { get; set; }
        public string NoTelepon { get; set; }
    }
}
