//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSakitWCF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TVaksinEntities2 : DbContext
    {
        public TVaksinEntities2()
            : base("name=TVaksinEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bpom> Bpom { get; set; }
        public virtual DbSet<laporanpenggunaanvaksin> laporanpenggunaanvaksin { get; set; }
        public virtual DbSet<Pasien> Pasien { get; set; }
        public virtual DbSet<Rumah_Sakit> Rumah_Sakit { get; set; }
        public virtual DbSet<Vaksin> Vaksin { get; set; }
    }
}
