//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSakitWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rumah_Sakit
    {
        public string IdRSakit { get; set; }
        public string NamaRSakit { get; set; }
        public string AlamatRSakit { get; set; }
        public string NoTelepon { get; set; }
        public long NikPasien { get; set; }
        public string NoRegisVaksin { get; set; }
    }
}
