//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPOM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class laporanpenggunaanvaksin
    {
        public string IdLaporanPeng { get; set; }
        public string IdBPOM { get; set; }
        public string IdRSakit { get; set; }
        public string NoRegisVaksin { get; set; }
        public long NikPasien { get; set; }
        public string NoRekamMedis { get; set; }
    }
}
