//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPOM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class laporankedatanganvaksin
    {
        public int IdLaporan { get; set; }
        public string NoRegisVaksin { get; set; }
        public string IdProdusen { get; set; }
        public string IdBPOM { get; set; }
        public string StatusVaksin { get; set; }
    }
}
