//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPOM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produsen
    {
        public string IdProdusen { get; set; }
        public string NamaProdusen { get; set; }
        public string AlamatProdusen { get; set; }
        public string NoTelepon { get; set; }
    }
}
